# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 867d498a88fb277abb0ace80808226c8a970df07e7e27fddd4418599a9ead30878a23c4d1e5d8f365980630aa9d98e69d1ea108b2de8c33a129286d4bc81ee5a

test:
  secret_key_base: 2560c252e63a4fd7ea1f7949e27aa11894bc3f2b735a1b0b717cde7983451978d255397b05426517217a55cca7e6e0c98d2d0b431d1997e65ca4e2af3b2225d3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
